import type { Post, Template } from './types';

export const mockPosts: Post[] = [
  {
    id: '1',
    author: 'CreativeWriter',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CreativeWriter',
    timestamp: '2 hours ago',
    title: 'Fantasy Adventure Epic Quest',
    description: 'Write a captivating fantasy adventure story about a group of heroes who set out on a perilous quest to retrieve a legendary artifact that is said to grant immense power. Describe the mystical lands they must travel through, the dangers they face, and the allies they make along the way.',
    image: 'https://images.unsplash.com/photo-1767709879762-c7a6ce819aeb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYW50YXN5JTIwYWR2ZW50dXJlJTIwbXlzdGljYWwlMjBsYW5kc2NhcGV8ZW58MXx8fHwxNzcyOTg0Mjc0fDA&ixlib=rb-4.1.0&q=80&w=1080',
    upvotes: 125,
    downvotes: 18,
    comments: 32,
    bookmarked: false,
    category: 'creative',
  },
  {
    id: '2',
    author: 'MarketeerPro',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MarketeerPro',
    timestamp: '5 hours ago',
    title: 'Eye-Catching Ad Copy',
    description: 'Craft a persuasive and attention-grabbing advertisement copy that highlights the unique selling points of a new tech gadget.',
    image: 'https://images.unsplash.com/photo-1758186366128-b7f4588ac75f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjB0ZWNobm9sb2d5JTIwZ2FkZ2V0fGVufDF8fHx8MTc3Mjg2NDY4OXww&ixlib=rb-4.1.0&q=80&w=1080',
    upvotes: 98,
    downvotes: 7,
    comments: 14,
    bookmarked: false,
    category: 'marketing',
  },
  {
    id: '3',
    author: 'Writer123',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Writer123',
    timestamp: '30 minutes ago',
    title: 'I need and loved the results. Great job!',
    description: 'Just wanted to share my experience with the community. The prompts are amazing!',
    upvotes: 45,
    downvotes: 2,
    comments: 8,
    bookmarked: false,
    category: 'discussion',
  },
  {
    id: '4',
    author: 'TechGuru',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TechGuru',
    timestamp: '1 day ago',
    title: 'API Integration Best Practices',
    description: 'Share your experience and best practices for integrating third-party APIs into modern web applications. What are the common pitfalls and how do you handle authentication securely?',
    image: 'https://images.unsplash.com/photo-1565229284535-2cbbe3049123?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2RpbmclMjBwcm9ncmFtbWluZyUyMGRldmVsb3BlcnxlbnwxfHx8fDE3NzI5MzMyNjZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    upvotes: 234,
    downvotes: 12,
    comments: 56,
    bookmarked: true,
    category: 'technical',
  },
  {
    id: '5',
    author: 'DesignEnthusiast',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DesignEnthusiast',
    timestamp: '3 hours ago',
    title: 'UI/UX Design Principles for 2026',
    description: 'Let\'s discuss the latest trends in UI/UX design. What principles are you following in your projects? How do you balance aesthetics with functionality?',
    image: 'https://images.unsplash.com/photo-1532623034127-3d92b01fb3c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmVhdGl2ZSUyMGRlc2lnbiUyMHdvcmtzcGFjZXxlbnwxfHx8fDE3NzI5NTIyMjZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    upvotes: 167,
    downvotes: 9,
    comments: 43,
    bookmarked: false,
    category: 'design',
  },
];

export const mockTemplates: Template[] = [
  {
    id: '1',
    title: 'Fantasy Adventure',
    icon: '🗡️',
  },
  {
    id: '2',
    title: 'Tech Product Review',
    icon: '💻',
  },
  {
    id: '3',
    title: 'Horror Story Starter',
    icon: '👻',
  },
];
